### ISSUE TITLE
Documentation: Create spreadsheet for stability and gain calculations for candidate op amps

### ISSUE THREAD

**Issue by meyerjohn** [eraticus/Safety-Shutter-Circuit#1]
Need this to determine applicability of a particular op amp, and maximum gain. Maximum gain might be limited by maximum resistor value is available.

**Comment by eraticus** [comment]
I did these calculations earlier for the feedback capacitor on the transconductive op amp circuits for the photodiode. Not sure if I need to preserve, but find the white paper that the work was based on for reference. I think it was a Microchip white paper

**Comment by eraticus** [comment]
Since the gain resistor has been reduced to 10K, this is no longer really necessary.
