### ISSUE TITLE
Create and test chopper amp noninverting circuit

### ISSUE THREAD

**Issue by meyerjohn** [eraticus/Safety-Shutter-Circuit#2]
Verify that basic noninverting op amp circuit will give zero (or near zero) output for V(inverting) == V(noninverting) == GND. Test this for high gains or high resistor values.

This is to test idea for suitability for second stage voltage amplifier circuit, if voltages from transimpedance stage are not high enough for ADC

**Comment by eraticus** [comment]
This might be a good idea to test. However, since we are not using a far IR diode, I'm going to close this for now. It would be a good idea to test a chopper amp within the current circuit architecture.
