### ISSUE TITLE
Find appropriate ADC with interrupt pin

### ISSUE THREAD

**Issue by meyerjohn** [eraticus/Safety-Shutter-Circuit#3]
It would be convenient to shutdown the microcontroller and communications while an ADC event is occurring so that switching noise does not affect the process.

The idea here is to initiate the ADC process, then sleep the controller. The controller when wakes when the ADC is finished and indicated by an interrupt pin. The controller can then read and communicate the values.

I believe that MAXIM has ADCs that operate at 5V, and have interrupt pins to indicate that a conversion is ready to read in.

**Comment by eraticus** [comment]
I did not find an ADC with an interrupt. So I designed the circuit with the MCP3008 10bit ADC.
