### ISSUE TITLE
Find values for photodiode

### ISSUE THREAD

**Issue by meyerjohn** [eraticus/Safety-Shutter-Circuit#4]
When Jaren did his Akamai project, he had expected current values that I would like to use in calculating op amp circuit gains. I also need to know what the capacitance of the photodiode is, in order to calculate stability, and capacitor compensation values.

This should be in my old notebook. If not, contact Jaren and Andre.

**Comment by eraticus** [comment]
Not using the far IR photodiodes. I use commercial 940nm photodiodes instead, since they will be mounted outside the dewar
