### ISSUE TITLE
Design NAND SR-Latch with avoidance of forbiden 00 state

### ISSUE THREAD

**Issue by meyerjohn** [eraticus/Safety-Shutter-Circuit#5]
I want to avoid both inputs going low, which would occur if there was an attempt to reset the latch when the circuit is currently faulting.

I have an idea of gating the input to S via an AND gate. By tying input A of the AND to R, the value of AND becomes a buffer for the B input. Attaching Y of AND to a 74HC05 makes it a NAND with OC output.

A 74HC03 chip is not a normally stocked part, but it is available.

**Comment by eraticus** [comment]
I'm closing this without rewiring the circuit for LOW/LOW input avoidance. This is because I don't anticipate this to be a problem. The interface via micro controller can check the state of the photodiodes first (via the fault lines).
