### ISSUE TITLE
Install MCP3008 10 bit ADC

### ISSUE THREAD

**Issue by meyerjohn** [eraticus/Safety-Shutter-Circuit#9]
Maybe don't write separate library, but have all code that interfaces with MCP3008 in a separate file.
[datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/21295d.pdf)

**Comment by eraticus** [comment]
The code for the MCP3008 is complete. There are some "improvements" that could be done, such as separating into a lib, and left justifying the data, and only using 8bits. I will wait for someone to ask me for this though. It works now.
